name: Markdown Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lintify:
    name: Verify Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: nosborn/github-action-markdown-cli@v3.0.1
        name: Markdownlint
        continue-on-error: true
        with:
          files: content/**/*.md
          config_file: ".markdownlint.json"
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          fail: true
          args: --no-progress './content/**/*.md' --accept 200..204,301..302,429 --exclude-file ./.lychee/.lycheeignore --cache --max-cache-age 1d .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
