name: Markdown Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    paths:
    - '**.md'

# jobs:
  # lintify:
  #   runs-on: ubuntu-latest

  #    steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: Run Markdown Lint
  #       uses: actionshub/markdownlint@main
  #       with:
  #         files: 'content/post/**/*.md'
  #         # Files or directories to ignore
  #         # ignore: # optional
  #         # Try to fix basic errors
  #         fix: true
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
        with:
          files: content/post/**/*.md
          fix: true
          config: .markdownlint.json
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: content/post
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.mlc_config.json'
          base-branch: main